
const analyzeButton = document.getElementById("analyze-button");
const clearButton = document.getElementById("clear-button");
const copyButton = document.getElementById("copy-result-button");
const userText = document.getElementById("user-text");
const resultContent = document.getElementById("result-content");
const charCount = document.getElementById("char-count");


userText.addEventListener("input", () => {
    charCount.textContent = `${userText.value.length} characters`;
});

function analyzeText(text) {
    const sentences = text.split(/[.!?]/).map(s => s.trim()).filter(Boolean);

    const wordCounts = sentences.map(s => (s.match(/\w+/g) || []).length);
    const averageLength = wordCounts.length ? wordCounts.reduce((a, b) => a + b, 0) / wordCounts.length : 0;

    const allWords = (text.match(/\w+/g) || []).map(w => w.toLowerCase());
    const totalWords = allWords.length;

    const stopwords = new Set([
        "the", "and", "is", "of", "in", "to", "a",
        "it", "that", "this", "for", "on", "with", "as"
    ]);

    const filteredWords = allWords.filter(word => !stopwords.has(word));
    const wordFrequency = {};
    filteredWords.forEach(word => {
        wordFrequency[word] = (wordFrequency[word] || 0) + 1;
    });

    let mostCommonWord = "";
    let highestCount = 0;
    for (const [word, count] of Object.entries(wordFrequency)) {
        if (count > highestCount) {
            mostCommonWord = word;
            highestCount = count;
        }
    }

    const repetitionRatio = totalWords ? highestCount / totalWords : 0;
    const uniqueWords = new Set(allWords).size;
    const lexicalDiversity = totalWords ? uniqueWords / totalWords : 0;

    const complexityScore = averageLength * 1.5 + repetitionRatio * 80 + (1 - lexicalDiversity) * 50;
    const result = complexityScore > 50
        ? "⚠️ This text is likely generated by an AI."
        : "✅ This text seems human-written.";

    return {
        result,
        average_length: averageLength.toFixed(2),
        most_common_word: mostCommonWord,
        highest_count: highestCount,
        lexical_diversity: lexicalDiversity.toFixed(2)
    };
}

analyzeButton.addEventListener("click", () => {
    const text = userText.value.trim();
    if (!text) return alert("Paste your text please!");

    const data = analyzeText(text);

    resultContent.innerHTML = `
        <p>${data.result}</p>
        <p>Average sentence length: ${data.average_length}</p>
        <p>Most common word: "${data.most_common_word}" (${data.highest_count} times)</p>
        <p>Lexical diversity: ${data.lexical_diversity}</p>
    `;
});


clearButton.addEventListener("click", () => {
    userText.value = "";
    resultContent.innerHTML = "";
    charCount.textContent = "0 characters";
});

copyButton.addEventListener("click", () => {
    navigator.clipboard.writeText(resultContent.innerText)
        .then(() => alert("Result copied!"))
        .catch(() => alert("Unable to copy."));
});